### ISSUE TITLE
`createDatabase` tries to connect to a not-yet-created database

### ISSUE THREAD

**Issue by moltar** [ozum/pg-test-util#17]
```ts
const mainConnection = await PgTestUtil.new({ connectionString: process.DATABASE_URL })
await mainConnection.createDatabase()
```

Explodes with:

```
VError: Cannot connect client for 'foo-69803_153228526398' database: password authentication failed for user "postgres"
```

```
      at Database._Database_getError (node_modules/pg-test-util/src/database.ts:59:4)
      at async Database.connect (node_modules/pg-test-util/src/database.ts:74:6)
      at async Function.new (node_modules/pg-test-util/src/database.ts:53:5)
      at async PgTestUtil.getDatabase (node_modules/pg-test-util/src/pg-test-util.ts:98:31)
      at async PgTestUtil.createDatabase (node_modules/pg-test-util/src/pg-test-util.ts:172:22)
```

If I log `args` in the `Database.new` method:

```
    args {
      clientConfig: {
        user: 'postgres',
        database: 'foo-69803_153228526398',
        port: 5432,
        host: 'localhost',
        binary: false,
        options: undefined,
        ssl: false,
        client_encoding: '',
        replication: undefined,
        isDomainSocket: false,
        application_name: undefined,
        fallback_application_name: undefined,
        statement_timeout: false,
        lock_timeout: false,
        idle_in_transaction_session_timeout: false,
        query_timeout: false,
        connect_timeout: 0,
        password: undefined
      },
      cleanup: [Function: cleanup],
      drop: [Function: drop]
    }
```

**Comment by ozum** [comment]
Thanks for reporting @moltar. It is fixed now, please update to the latest version.

**Comment by moltar** [comment]
Thank you!! Works great now 🎉
